name: open_pr

on: 
  pull_request:
    types: [opened]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Call API
        run: |
          curl --request POST \
            --url https://circleci.com/api/v2/project/gh/ryanpedersen42/dummy-pr-test/pipeline \
            --header 'content-type: application/json' \
            --header 'Circle-Token: ${{ secrets.CIRCLE_TOKEN }}' \
            --data '{"branch":"some_branch","tag":"some_tag","parameters":{"pr_from_gh":true}}'
