name: pr_test

on: pull_request

jobs:
  build:
    env: # Or as an environment variable
      CIRCLE_API_TOKEN: ${{ secrets.CIRCLE_API_TOKEN }}
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set envars
        run: |
          echo "export TOKEN=$CIRCLE_API_TOKEN" >> $BASH_ENV
      - name: call API
        run: |
          curl --request POST \
            --url https://circleci.com/api/v2/project/gh/ryanpedersen42/dummy-pr-test/pipeline \
            --header 'content-type: application/json' \
            --header 'Circle-Token: ${TOKEN}' \