name: pr_test

on: pull_request

jobs:
  build:

    env: 
      CIRCLE_API_TOKEN: ${{ secrets.CIRCLE_TOKEN }}

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Call API 1
        run: |
          curl --request POST \
            --url https://circleci.com/api/v2/project/gh/ryanpedersen42/dummy-pr-test/pipeline \
            --header 'content-type: application/json' \
            --header 'Circle-Token: ${{ secrets.CIRCLE_TOKEN }}' \
      # - name: Call API 2
      #   run: |
      #     curl --request POST \
      #       --url https://circleci.com/api/v2/project/gh/ryanpedersen42/dummy-pr-test/pipeline \
      #       --header 'content-type: application/json' \
      #       --header 'Circle-Token: ${{ secrets.CIRCLE_TOKEN }}' \
      # - name: Call API 3
      #   run: |
      #     curl --request POST \
      #       --url https://circleci.com/api/v2/project/gh/ryanpedersen42/dummy-pr-test/pipeline \
      #       --header 'content-type: application/json' \
      #       --header 'Circle-Token: ${{ secrets.CIRCLE_TOKEN }}' \